import { Center } from 'native-base';
import {StyleSheet} from 'react-native';


export const styles = StyleSheet.create({

    flexrow:{
        flexDirection:'row',
    },
    container: {
        marginTop:50,
        flexDirection:'row',  
    },
    whiteback: {
        backgroundColor:'#e6ebf1',
        paddingBottom:800,
    },
    arrow: {   
        marginLeft:20,
        marginTop:20,
    },
    clean1:{
        position:'absolute',
        width:50,
        height:50,
        marginLeft:160,
        marginTop:-30,
    },
    clean2:{
        position:'absolute',
        width:50,
        height:50,
        marginLeft:-20,
        marginTop:20,
    },
    clean4:{
        position:'absolute',
        width:70,
        height:70,
        marginLeft:global.screenwidth - 60,
        marginTop:10,
    },
    clean6:{
        marginTop:30,
        marginLeft:global.screenwidth - 100,
        width:120,
        height:120,
        position:'absolute',
    },
    polygon1:{
        marginLeft:global.screenwidth - 90,
        marginTop:-20,
    },
    woman1:{
        marginTop:-70,
        justifyContent:'center',
        alignItems:'center',
    },
    toprect: {
        width:global.screenwidth,
        height:350,
        backgroundColor:'#562b63',
        borderBottomLeftRadius:20,
        borderBottomRightRadius:20,
        marginTop:-50,  
    },
    top1: {
        flexDirection: 'row',
        marginLeft:50,
        marginTop:15,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
    },
    toptext1:{
        flexDirection: 'row',
        marginLeft:50,
        marginTop:50,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
    },
    toptext2:{
        flexDirection: 'row',
        marginLeft:50,
        marginTop:75,
        fontSize:24,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
    },
    toptext3:{
        marginLeft:50,
        marginTop:120,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
    },
    toptext4:{
        marginLeft:60,
        marginTop:150,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
        borderRadius:10,
        backgroundColor:"#4d812f",
        width:70,
        textAlign:'center',
        borderColor:'white',
        borderWidth:2,

    },
    toptext5:{
        // flexDirection: 'row',
        marginLeft:50,
        marginTop:120,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
        alignSelf:'flex-end',
    },
    toptext6:{
        marginLeft:-80,
        marginTop:150,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
        borderRadius:10,
        backgroundColor:"#8c1c32",
        width:70,
        textAlign:'center',
        borderColor:'white',
        borderWidth:2,
        // alignSelf:'flex-end',
    },
    toptext8:{
        marginLeft:-45,
    },
    contenttext1:{
        margin:20,
        fontSize:16,
    },
    contenttext2:{
        marginTop:15,
        paddingTop:7,
        backgroundColor:'#0bbc6e',
        width:190,
        height:40,
        borderRadius:30,
        fontSize:16,
        color:'white',
        textAlign:'center',
        fontWeight:'bold',
    },
    content:{
        width:global.screenwidth - 40,
        height:global.screenheight - 320,
        backgroundColor:'white',
        borderRadius:20,
        marginLeft:20,
        marginRight:20,
        marginTop:-110,
    },
    dline: {                    
        borderBottomColor: '#555555',
        borderBottomWidth: 2,
        marginTop:5,
        marginBottom:5,
        width:global.screenwidth - 40,     
    },
    dline1: {                    
        borderBottomColor: '#eeeeee',
        borderBottomWidth: 2,
        marginTop:10,
        width:global.screenwidth - 40,     
    },
    contenttext3:{
        marginLeft:20,
        marginTop:5,
        fontSize:18,
        fontWeight:'bold',
        color:'#444444',
    },
    contenttext4:{
        marginLeft:20,
        fontSize:14,
        fontWeight:'bold',
        color:'#888888',
    },
    contenttext5:{
        marginLeft: 'auto',
        marginTop:15,
    },
    contenttext6:{
        marginRight:30,
        fontSize:16,
        color:"#439b73",
        fontWeight:'bold',
    },
    contenttext7:{
        marginRight:30,
        fontSize:16,
        color:"#c84348",
        fontWeight:'bold',
    },
    mid2:{
        flexDirection:'row',
        width:global.screenwidth - 40,     
    },
    mid3:{
        flexDirection:'row',
        width:global.screenwidth - 40,     
    },
    
    bottommenu0:{
        marginTop:global.screenheight - 85,
        position:'absolute'
    },
    
})