import { Center } from 'native-base';
import {StyleSheet} from 'react-native';


export const styles = StyleSheet.create({

    flexrow:{
        flexDirection:'row',
    },
    container: {
        marginTop:50,
        flexDirection:'row',  
    },
    whiteback: {
        backgroundColor:'#e6ebf1',
        paddingBottom:800,
    },
    arrow: {   
        marginLeft:20,
        marginTop:20,
    },
    clean1:{
        position:'absolute',
        width:50,
        height:50,
        marginLeft:160,
        marginTop:-30,
    },
    clean2:{
        position:'absolute',
        width:50,
        height:50,
        marginLeft:-20,
        marginTop:20,
    },
    clean4:{
        position:'absolute',
        width:70,
        height:70,
        marginLeft:global.screenwidth - 60,
        marginTop:10,
    },
    clean6:{
        marginTop:30,
        marginLeft:global.screenwidth - 100,
        width:120,
        height:120,
        position:'absolute',
    },
    polygon1:{
        marginLeft:global.screenwidth - 90,
        marginTop:-20,
    },
    woman1:{
        marginTop:-70,
        justifyContent:'center',
        alignItems:'center',
    },
    toprect: {
        width:global.screenwidth,
        height:350,
        backgroundColor:'#562b63',
        borderBottomLeftRadius:20,
        borderBottomRightRadius:20,
        marginTop:-50,  
    },
    top1: {
        flexDirection: 'row',
        marginLeft:50,
        marginTop:15,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
    },
    toptext1:{
        flexDirection: 'row',
        marginLeft:50,
        marginTop:50,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
    },
    toptext2:{
        flexDirection: 'row',
        marginLeft:50,
        marginTop:75,
        fontSize:24,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
    },
    toptext3:{
        marginLeft:50,
        marginTop:120,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
    },
    toptext4:{
        marginLeft:60,
        marginTop:150,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
        borderRadius:10,
        backgroundColor:"#4d812f",
        width:70,
        textAlign:'center',
        borderColor:'white',
        borderWidth:2,

    },
    toptext5:{
        // flexDirection: 'row',
        marginLeft:50,
        marginTop:120,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
        alignSelf:'flex-end',
    },
    toptext6:{
        marginLeft:-80,
        marginTop:150,
        fontSize:16,
        color:'white',
        fontWeight:'bold',
        position:'absolute',
        borderRadius:10,
        backgroundColor:"#8c1c32",
        width:70,
        textAlign:'center',
        borderColor:'white',
        borderWidth:2,
        // alignSelf:'flex-end',
    },
    toptext8:{
        marginLeft:-45,
    },
    contenttext1:{
        marginTop:15,
        // marginBottom:10,
        fontSize:18,
        color:'#562b63',
        fontWeight:'bold',
        textAlign:'center',
    },
    content:{
        width:global.screenwidth - 40,
        height:global.screenheight - 320,
        backgroundColor:'white',
        borderRadius:20,
        marginLeft:20,
        marginRight:20,
        marginTop:-110,
    },
    dline: {                    
        borderBottomColor: '#562b63',
        borderBottomWidth: 1,
        marginTop:10,
        // marginBottom:10,
        width:global.screenwidth - 40,     
    },
    dline1: {                    
        borderBottomColor: '#dddddd',
        borderBottomWidth: 1,
        marginTop:10,
        marginBottom:5,
        width:global.screenwidth - 40,     
    },
    content1:{
        flexDirection:'row',
        marginLeft:20,
    },
    service:{
        color:"#562b63",
        fontSize:16,
        fontWeight:"bold",
        marginTop:10,
        marginLeft:20,
        marginRight:20,
        width: (global.screenwidth -180)/3,   
    },
    cleaning:{
        color:"#888888",
        fontSize:15,
        fontWeight:"bold",
        // marginTop:10,
        marginLeft:20,
        marginRight:20,
        width: (global.screenwidth -180)/3,   
    },
    cleaning1:{
        color:"#1bb076",
        fontSize:15,
        fontWeight:"bold",
        // marginTop:10,
        marginLeft:20,
        marginRight:20,
    },
    date:{
        marginLeft:40,
        // marginTop:5,
        fontSize:14,
        color:"#888888",
    },
    state:{
        marginLeft:20,
        marginTop:5,
        fontSize:12,
        color:"#555555",
    },
    workdone:{
        marginLeft:5,
        marginTop:3,
        fontSize:14,
        color:"#1bb076",
    },
    Progress:{
        marginLeft:5,
        marginTop:3,
        fontSize:14,
        color:"#f29649",

    },



    bottommenu0:{
        marginTop:global.screenheight - 85,
        position:'absolute'
    },
    
})